const eventsData = {
    keys: ["title", "year", "type", "testament", "books", "passages", "description", "keyTheme", "jesus", "funFact"],
    data: [
        [
            "Creation",
            "Genesis 1-2",
            "major",
            "ot",
            ["Genesis"],
            ["Genesis 1:1", "Genesis 1:26-27"],
            "God creates the heavens, earth, and humanity, establishing His design for creation and giving humans the unique role of bearing His image and reflecting His glory.",
            "God is the Creator, and humanity is created to reflect His image and represent Him on earth.",
            "Jesus is the eternal Word through whom all things were created, showing that Christ was active from the beginning of creation.",
            "The first recorded words of God in Scripture are 'Let there be light,' showing the power of God's spoken word."
        ],
        [
            "The Fall",
            "Genesis 3",
            "major",
            "ot",
            ["Genesis"],
            ["Genesis 3:15"],
            "Adam and Eve disobey God in the Garden of Eden, bringing sin, suffering, and separation from God into the world.",
            "Humanity's greatest problem is sin, but God immediately reveals His plan to bring redemption.",
            "The promised offspring of Eve points forward to Jesus, who defeats sin and Satan through His saving work.",
            "Genesis 3:15 is called the first gospel promise because it is the earliest announcement of God's victory over evil."
        ],
        [
            "The Flood",
            "Genesis 6-9",
            "minor",
            "ot",
            ["Genesis"],
            ["Genesis 6:13", "Genesis 9:12-13"],
            "God judges the widespread corruption of humanity through the flood while preserving Noah, his family, and representatives of creation.",
            "God judges evil but provides a way of salvation for those who trust and obey Him.",
            "The ark points forward to Christ as the ultimate refuge and means of salvation from judgment.",
            "God established the rainbow covenant with Noah as a sign of His promise never again to destroy the earth with a flood."
        ],
        [
            "The Tower of Babel",
            "Approx. 2200 BC",
            "major",
            "ot",
            ["Genesis"],
            ["Genesis 11:1-9"],
            "Humanity attempts to build a tower to make a name for themselves, leading God to confuse their languages and disperse them across the earth.",
            "Humanity's pride and desire for self-glory are thwarted by God, who initiates the dispersion of nations to prepare for His plan to gather them through Abraham.",
            "Jesus reverses the division of Babel by gathering people from every tribe, tongue, and nation into one family through the power of the Holy Spirit.",
            "Pentecost reversed Babel—where God confused languages to scatter humanity because of pride, the Holy Spirit enabled people of many languages to hear the gospel and be united in Christ."
        ],
        [
            "Abraham Covenant",
            "Around 2000 BC",
            "major",
            "ot",
            ["Genesis"],
            ["Genesis 12", "Genesis 15"],
            "God calls Abraham and promises him land, descendants, and blessing, beginning His plan to bless all nations through one family.",
            "God begins His redemption plan through Abraham's family and extends His blessing to the entire world.",
            "Jesus fulfills God's promise to Abraham by bringing salvation and blessing to all nations.",
            "Abraham was 75 years old when God called him, showing that God's purposes are not limited by human age."
        ],
        [
            "Isaac Born",
            "Genesis 21",
            "minor",
            "ot",
            ["Genesis"],
            ["Genesis 21"],
            "God fulfills His promise by giving Abraham and Sarah a son, demonstrating His faithfulness despite their old age and impossible circumstances.",
            "God faithfully keeps His promises even when fulfillment seems impossible from a human perspective.",
            "Isaac's miraculous birth points to God's ability to fulfill His promises through His chosen plan.",
            "Isaac's name means 'he laughs' because Abraham and Sarah laughed when God promised them a son."
        ],
        [
            "Jacob Becomes Israel",
            "Genesis 25–35",
            "minor",
            "ot",
            ["Genesis"],
            ["Genesis 32:28", "Genesis 35:10"],
            "God continues His covenant promise through Jacob, whose twelve sons become the foundation of the twelve tribes of Israel.",
            "God's promises continue through generations despite human weakness and failure.",
            "God's covenant line leads to Jesus, the promised descendant who brings blessing to all nations.",
            "Jacob's name was changed to Israel, and his twelve sons became the ancestors of the twelve tribes of Israel."
        ],
        [
            "The Story of Joseph",
            "Genesis 37-50",
            "major",
            "ot",
            ["Genesis"],
            ["Genesis 37:28", "Genesis 50:20"],
            "Betrayed by his brothers and sold into Egyptian slavery, Joseph rises to power by God's providence, saving the region from famine and preserving the family line of Abraham.",
            "God's providence and sovereignty work through human sin to accomplish His purposes and bring blessing.",
            "Like Joseph, Jesus was rejected and betrayed by His own people, falsely accused, and ultimately exalted to save the world and extend forgiveness to His betrayers.",
            "Joseph is one of the few major Bible figures with no recorded personal sin, making him one of the clearest Old Testament pictures (types) of Christ."
        ],
        [
            "God Forms Israel as His People",
            "1446 BC",
            "major",
            "ot",
            ["Exodus", "Leviticus", "Deuteronomy"],
            ["Exodus 19:5-6", "Deuteronomy 7:6"],
            "God forms the descendants of Abraham into a covenant nation, calling Israel to know Him, reflect His character, and bless the nations.",
            "God chooses Israel to reveal His purposes and serve as His witness among the nations.",
            "Jesus fulfills Israel's calling by becoming the faithful Son who brings God's blessing to all peoples.",
            "Israel was called a 'kingdom of priests,' showing their purpose was to represent God to the world."
        ],
        [
            "Exodus",
            "1446 BC",
            "major",
            "ot",
            ["Exodus", "Leviticus", "Numbers", "Deuteronomy"],
            ["Exodus 3", "Exodus 12", "Exodus 19-20"],
            "God calls Moses to deliver Israel from slavery in Egypt, rescues His people through the Passover, and establishes His covenant with them at Mount Sinai.",
            "God redeems His people and forms them into a covenant nation for His purposes.",
            "The Passover lamb points to Jesus, whose sacrifice brings ultimate freedom from sin.",
            "Moses' life is divided into three 40-year periods: Egypt, Midian, and leading Israel through the wilderness."
        ],
        [
            "Ten Commandments",
            "1446 BC",
            "minor",
            "ot",
            ["Exodus"],
            ["Exodus 20"],
            "God gives Israel His law at Mount Sinai, teaching them how to live as His covenant people and reflect His holiness.",
            "God teaches His redeemed people how to live in faithful relationship with Him.",
            "Jesus fulfills the law perfectly and reveals its true purpose through His teaching and life.",
            "The first tablets were broken by Moses after Israel worshiped the golden calf. God later gave a second set of tablets that were kept in the Ark of the Covenant."
        ],
        [
            "Conquest of Canaan",
            "1406 BC",
            "minor",
            "ot",
            ["Joshua"],
            ["Joshua 1:1-9"],
            "Under Joshua's leadership, Israel enters the Promised Land as God fulfills His covenant promise to Abraham.",
            "God faithfully fulfills His promises and leads His people into the inheritance He prepared for them.",
            "Joshua's name means Yeshua, pointing forward to Jesus who brings ultimate salvation.",
            "Joshua and Jesus share the same Hebrew name, Yeshua, meaning 'The LORD saves.'"
        ],
        [
            "Era of Judges",
            "1375–1050 BC",
            "minor",
            "ot",
            ["Judges", "Ruth"],
            ["Judges 2:16"],
            "Israel repeatedly turns away from God, but He raises judges to rescue them from oppression and restore them.",
            "Human leaders fail, revealing humanity's need for a perfect and eternal King.",
            "Jesus is the ultimate Judge and Redeemer who delivers His people forever.",
            ""
        ],
        [
            "Davidic Covenant",
            "1000 BC",
            "major",
            "ot",
            ["1 Samuel", "2 Samuel", "Psalms"],
            ["2 Samuel 7"],
            "God promises David that his family line will continue forever and that an everlasting kingdom will come through his descendant.",
            "God promises an eternal King from David's family who will rule with everlasting authority.",
            "Jesus is the promised Son of David who establishes God's eternal kingdom.",
            "David wanted to build God a house, but God promised to build David a lasting dynasty instead."
        ],
        [
            "Solomon's Temple",
            "960 BC",
            "minor",
            "ot",
            ["1 Kings", "2 Chronicles"],
            ["1 Kings 6"],
            "Solomon builds the first permanent Temple in Jerusalem, creating a central place where Israel worships God and experiences His covenant presence among His people.",
            "God desires to dwell among His people, pointing toward His ultimate presence through Christ.",
            "Jesus is the greater Temple where God's presence is fully revealed and where humanity meets God.",
            "The first Temple took seven years to build and remained the center of Israel's worship for almost 400 years."
        ],
        [
            "The United Kingdom",
            "1050–930 BC",
            "major",
            "ot",
            ["1 Samuel", "2 Samuel", "1 Kings"],
            ["1 Samuel 8", "1 Samuel 12"],
            "Israel transitions from a loose confederation of tribes under judges to a centralized monarchy under Saul, David, and Solomon, establishing Jerusalem as the political and spiritual capital.",
            "God is the true King, but He allows an earthly monarchy to point toward the need for the ultimate, perfect King who will reign forever.",
            "Jesus is the True King of kings who establishes an eternal, spiritual kingdom that will never be divided or destroyed.",
            "The people demanded a king to be like the surrounding nations, but God warned them that an earthly king would bring both benefits and heavy burdens."
        ],
        [
            "The Kingdom Divided",
            "930 BC",
            "major",
            "ot",
            ["1 Kings", "2 Chronicles"],
            ["1 Kings 12"],
            "After Solomon's reign, Israel divides into the Northern Kingdom and Southern Kingdom because of rebellion and unfaithfulness.",
            "A divided kingdom reveals the consequences of rejecting God's rule and the need for a faithful King.",
            "Jesus comes as the greater Son of David who restores God's kingdom and gathers God's people together.",
            "The Northern Kingdom had many kings, but none were described as faithful to God in the same way as David."
        ],
        [
            "Ministry of Elijah/Elisha",
            "870–790 BC",
            "minor",
            "ot",
            ["1 Kings", "2 Kings"],
            ["1 Kings 17", "2 Kings 2"],
            "Elijah and Elisha serve as prophets during a time of spiritual decline, calling Israel back to worship the true God and trust His word.",
            "God remains faithful by sending prophets to call His people back to covenant faithfulness.",
            "Their prophetic ministries point forward to Jesus, the ultimate prophet who reveals God's truth.",
            "Elijah was taken to heaven in a whirlwind without experiencing ordinary death, one of Scripture's most unusual events."
        ],
        [
            "Ministry of Isaiah",
            "740–680 BC",
            "minor",
            "ot",
            ["Isaiah"],
            ["Isaiah 7:14", "Isaiah 53"],
            "Isaiah proclaims God's judgment against sin while revealing hope through prophecies about the coming Messiah and suffering servant.",
            "God reveals both judgment and salvation through the promised coming Messiah.",
            "Isaiah's prophecies point clearly to Jesus as the suffering servant and promised Savior.",
            "Isaiah 53 describes the suffering servant centuries before Jesus' death and is one of the clearest Messianic prophecies."
        ],
        [
            "Ministry of Jeremiah",
            "627–586 BC",
            "minor",
            "ot",
            ["Jeremiah"],
            ["Jeremiah 31:31-34"],
            "Jeremiah warns Judah of coming judgment while announcing God's promise of a New Covenant.",
            "God judges rebellion but promises restoration and a renewed relationship with His people.",
            "The New Covenant promise finds its fulfilment through Jesus' sacrifice and the forgiveness He brings.",
            "Jeremiah is known as the 'weeping prophet' because he grieved over Judah's rejection of God."
        ],
        [
            "Babylonian Exile",
            "586 BC",
            "major",
            "ot",
            ["Jeremiah", "Lamentations", "Ezekiel", "Daniel"],
            ["Jeremiah 31:31", "Ezekiel 36:26"],
            "Babylon destroys Jerusalem and takes Judah into exile, while prophets like Ezekiel bring messages of judgment, restoration, and future hope.",
            "God disciplines His people but promises restoration through a New Covenant and transformed hearts.",
            "The New Covenant promises find fulfillment through Jesus, who brings forgiveness and a renewed relationship with God.",
            ""
        ],
        [
            "Return from Exile & Second Temple",
            "538–516 BC",
            "major",
            "ot",
            ["Ezra", "Nehemiah", "Haggai", "Zechariah"],
            ["Ezra 1:1-4", "Ezra 6:15"],
            "Led by Zerubbabel, Ezra, and Nehemiah, the Jews return to Jerusalem from Babylon to rebuild the Temple and restore the city walls.",
            "God is faithful to His promise of restoration; even after judgment, He provides a way for His people to return and worship Him.",
            "Jesus arrives as the ultimate fulfillment of the Temple, representing the true place where God dwells with His people forever.",
            "The Second Temple was built without the Ark of the Covenant, making it one of the greatest mysteries of the Bible since the Ark disappeared before or during the Babylonian exile."
        ],
        [
            "Birth of Jesus",
            "AD 0",
            "major",
            "nt",
            ["Matthew", "Luke"],
            ["Matthew 1", "Luke 2"],
            "Jesus, the promised Messiah and Son of God, is born in Bethlehem, bringing God's salvation plan into human history through the incarnation.",
            "God fulfills His promises by entering His creation and becoming present with humanity.",
            "",
            "Bethlehem was the city of David, connecting Jesus' birth to the royal promise God made to David."
        ],
        [
            "Jesus' Ministry",
            "AD 27–30",
            "major",
            "nt",
            ["Matthew", "Mark", "Luke", "John"],
            ["Mark 1:14-15", "Luke 4:18-19"],
            "Jesus announces the arrival of God's kingdom, teaches truth, performs miracles, and reveals God's character through His life and ministry.",
            "Jesus reveals God's kingdom and shows that God's saving purpose has arrived through Him.",
            "",
            "Jesus' ministry lasted about three years, yet it transformed history and continues to impact billions of people."
        ],
        [
            "Cross and Resurrection",
            "AD 30",
            "major",
            "nt",
            ["Matthew", "Mark", "Luke", "John"],
            ["Isaiah 53", "Luke 24"],
            "Jesus dies on the cross for sin and rises from the dead, accomplishing God's plan of redemption and defeating the power of death.",
            "Jesus completes God's salvation plan by defeating sin, death, and separation from God.",
            "",
            ""
        ],
        [
            "Pentecost: The Church Begins",
            "AD 30–33",
            "major",
            "nt",
            ["Acts"],
            ["Acts 2"],
            "The Holy Spirit comes at Pentecost, empowering Jesus' followers to proclaim the gospel and forming the early Church.",
            "God's presence now dwells within His people through the Holy Spirit, continuing His mission in the world.",
            "",
            "At Pentecost, people from many nations heard the gospel in their own languages, showing God's salvation is for all peoples."
        ],
        [
            "The Gospel Spreads to the Nations",
            "AD 30–60",
            "major",
            "nt",
            ["Acts"],
            ["Acts 1:8", "Acts 13"],
            "The Holy Spirit empowers the early Church to spread the gospel from Jerusalem to Judea, Samaria, and the nations.",
            "God's salvation plan expands beyond Israel to include people from every nation.",
            "",
            "The book of Acts begins in Jerusalem and ends with the gospel reaching Rome, showing the expansion of God's mission."
        ],
        [
            "The Apostles' Writings",
            "AD 50–95",
            "minor",
            undefined,
            [
                "Romans",
                "1 Corinthians",
                "Hebrews",
                "James",
                "1 Peter",
                "Revelation"
            ],
            [
                "Romans 1:16",
                "1 Corinthians 15:1-4",
                "Revelation 21:1-5"
            ],
            "The apostles teach the Church the meaning of Jesus' life, death, and resurrection while guiding believers to live faithfully as they await His return.",
            "God's people live between Christ's first coming and His future return, continuing His mission with hope.",
            "",
            "The Apostle Paul, author of 13 New Testament books — began as a zealous persecutor of Christians, actively hunting down and arresting believers before his dramatic conversion to faith in Christ."
        ],
        [
            "New Creation",
            "Future Promise",
            "major",
            "nt",
            ["Revelation"],
            ["Revelation 21:1-5", "Revelation 22:1-5"],
            "God restores creation, removes the effects of sin, and brings His people into eternal fellowship with Him in the renewed heavens and earth.",
            "The Bible ends with God's original purpose fulfilled: dwelling with humanity in a restored creation.",
            "",
            "The Bible begins with a garden in Genesis and ends with a restored creation in Revelation, showing God's complete redemption story."
        ]
    ]
};